<?

$towns = array(
array('name' => 'Одинцово и Одинцовский район',	'secondName' => 'Одинцово и Одинцовском районе'),
array('name' => 'Люберцы и Люберецкий район ',	'secondName' => 'Люберцах и Люберецком районе '),
array('name' => 'Раменское и Раменский район ',	'secondName' => 'Раменском и Раменском районе '),
array('name' => 'Сергиев Посад и Сергиево-Посадский район ',	'secondName' => 'Сергиевом Посаде и Сергиево-Посадском районе '),
array('name' => 'Красногорск и Красногорский район ',	'secondName' => 'Красногорске и Красногорском районе '),
array('name' => 'Ногинск и Ногинский район ',	'secondName' => 'Ногинске и Ногинском районе '),
array('name' => 'Щёлково и Щёлковский район ',	'secondName' => 'Щёлково и Щёлковском районе '),
array('name' => 'Пушкино и Пушкинский район ',	'secondName' => 'Пушкино и Пушкинском районе '),
array('name' => 'Дмитров и Дмитровский район ',	'secondName' => 'Дмитрове и Дмитровском районе '),
array('name' => 'Воскресенск и Воскресенский район ',	'secondName' => 'Воскресенске и Воскресенском районе '),
array('name' => 'Наро-Фоминск и Наро-Фоминский район ',	'secondName' => 'Наро-Фоминске и Наро-Фоминском районе '),
array('name' => 'Солнечногорск и Солнечногорский район ',	'secondName' => 'Солнечногорске и Солнечногорском районе '),
array('name' => 'Клин и Клинский район ',	'secondName' => 'Клине и Клинском районе '),
array('name' => 'Чехов и Чеховский район ',	'secondName' => 'Чехове и Чеховском районе '),
array('name' => 'Ступино и Ступинский район ',	'secondName' => 'Ступино и Ступинском районе '),
array('name' => 'Истра и Истринский район ',	'secondName' => 'Истре и Истринском районе '),
array('name' => 'Орехово-Зуево и Орехово-Зуевский район ',	'secondName' => 'Орехово-Зуево и Орехово-Зуевском районе '),
array('name' => 'Видное и Ленинский район ',	'secondName' => 'Видном и Ленинском районе '),
array('name' => 'Павловский Посад и Павлово-Посадский район ',	'secondName' => 'Павловском Посаде и Павлово-Посадском районе '),
array('name' => 'Можайск и Можайский район ',	'secondName' => 'Можайске и Можайском районе '),
array('name' => 'Шатура и Шатурский район ',	'secondName' => 'Шатуре и Шатурском районе '),
array('name' => 'Руза и Рузский район ',	'secondName' => 'Рузе и Рузском районе '),
array('name' => 'Луховицы и Луховицкий район ',	'secondName' => 'Луховицах и Луховицком районе '),
array('name' => 'Талдом и Талдомский район ',	'secondName' => 'Талдоме и Талдомском районе '),
array('name' => 'Коломна и Коломенский район ',	'secondName' => 'Коломне и Коломенском районе '),
array('name' => 'Волоколамск и Волоколамский район ',	'secondName' => 'Волоколамске и Волоколамском районе '),
array('name' => 'Зарайск и Зарайский район ',	'secondName' => 'Зарайске и Зарайском районе '),
array('name' => 'Серпухов и Серпуховский район ',	'secondName' => 'Серпухове и Серпуховском районе '),
array('name' => 'Лотошино и Лотошинский район ',	'secondName' => 'Лотошино и Лотошинском районе '),
array('name' => 'Балашиха',	'secondName' => 'Балашихе'),
array('name' => 'Дедовск',	'secondName' => 'Дедовске'),
array('name' => 'Дзержинский',	'secondName' => 'Дзержинском'),
array('name' => 'Долгопрудный',	'secondName' => 'Долгопрудном'),
array('name' => 'Домодедово',	'secondName' => 'Домодедово'),
array('name' => 'Дубна',	'secondName' => 'Дубне'),
array('name' => 'Егорьевск',	'secondName' => 'Егорьевске'),
array('name' => 'Железнодорожный',	'secondName' => 'Железнодорожном'),
array('name' => 'Жуковский',	'secondName' => 'Жуковском'),
array('name' => 'Кашира',	'secondName' => 'Кашире'),
array('name' => 'Климовск',	'secondName' => 'Климовске'),
array('name' => 'Королёв',	'secondName' => 'Королёве'),
array('name' => 'Котельники',	'secondName' => 'Котельниках'),
array('name' => 'Краснознаменск',	'secondName' => 'Краснознаменске'),
array('name' => 'Ликино-Дулёво',	'secondName' => 'Ликино-Дулёво'),
array('name' => 'Лобня',	'secondName' => 'Лобне'),
array('name' => 'Лыткарино',	'secondName' => 'Лыткарино'),
array('name' => 'Мытищи',	'secondName' => 'Мытищах'),
array('name' => 'Подольск',	'secondName' => 'Подольске'),
array('name' => 'Протвино',	'secondName' => 'Протвино'),
array('name' => 'Реутов',	'secondName' => 'Реутове'),
array('name' => 'Фрязино',	'secondName' => 'Фрязино'),
array('name' => 'Химки',	'secondName' => 'Химках'),
array('name' => 'Электросталь',	'secondName' => 'Электростали'),
array('name' => 'Юбилейный',	'secondName' => 'Юбилейном'),
array('name' => 'Красноармейск',	'secondName' => 'Красноармейске'),
array('name' => 'Кубинка',	'secondName' => 'Кубинке'),
array('name' => 'Озёры',	'secondName' => 'Озёры'),
array('name' => 'Лосино-Петровский',	'secondName' => 'Лосино-Петровском'),
array('name' => 'Хотьково',	'secondName' => 'Хотьково'),
array('name' => 'Электрогорск',	'secondName' => 'Электрогорске'),
array('name' => 'Старая Купавна',	'secondName' => 'Старой Купавне'),
array('name' => 'Черноголовка',	'secondName' => 'Черноголовке'),
array('name' => 'Рошаль',	'secondName' => 'Рошале'),
array('name' => 'Пущино',	'secondName' => 'Пущино'),
array('name' => 'Электроугли',	'secondName' => 'Электроуглях'),
array('name' => 'Бронницы',	'secondName' => 'Бронницах'),
array('name' => 'Яхрома',	'secondName' => 'Яхроме'),
array('name' => 'Дрезна',	'secondName' => 'Дрезне'),
array('name' => 'Высоковск',	'secondName' => 'Высоковске'),
array('name' => 'Ожерелье',	'secondName' => 'Ожерелье'),
array('name' => 'Апрелевка',	'secondName' => 'Апрелевке'),
array('name' => 'Куровское',	'secondName' => 'Куровском'),
array('name' => 'Голицыно',	'secondName' => 'Голицыно'),
array('name' => 'Звенигород',	'secondName' => 'Звенигороде'),
array('name' => 'Пересвет',	'secondName' => 'Пересвете'),
array('name' => 'Краснозаводск',	'secondName' => 'Краснозаводске'),
array('name' => 'Авсюнино',	'secondName' => 'Авсюнино'),
array('name' => 'Акулово',	'secondName' => 'Акулово'),
array('name' => 'Алабино',	'secondName' => 'Алабино'),
array('name' => 'Алабушево',	'secondName' => 'Алабушево'),
array('name' => 'Ангелово',	'secondName' => 'Ангелово'),
array('name' => 'Аникеевка',	'secondName' => 'Аникеевке'),
array('name' => 'Архангельское',	'secondName' => 'Архангельском'),
array('name' => 'Атепцево',	'secondName' => 'Атепцево'),
array('name' => 'Бавыкино',	'secondName' => 'Бавыкино'),
array('name' => 'Балобаново',	'secondName' => 'Балобаново'),
array('name' => 'Баранцево',	'secondName' => 'Баранцево'),
array('name' => 'Барвиха',	'secondName' => 'Барвихе'),
array('name' => 'Барыбино',	'secondName' => 'Барыбино'),
array('name' => 'Бекасово',	'secondName' => 'Бекасово'),
array('name' => 'Белая Дача',	'secondName' => 'Белой Даче'),
array('name' => 'Белеутово',	'secondName' => 'Белеутово'),
array('name' => 'Белые Столбы',	'secondName' => 'Белых Столбах'),
array('name' => 'Беляниново',	'secondName' => 'Беляниново'),
array('name' => 'Бершово',	'secondName' => 'Бершово'),
array('name' => 'Беседы',	'secondName' => 'Беседах'),
array('name' => 'Бисерово',	'secondName' => 'Бисерово'),
array('name' => 'Богданиха',	'secondName' => 'Богданихе'),
array('name' => 'Болтино',	'secondName' => 'Болтино'),
array('name' => 'Большие Вязёмы',	'secondName' => 'Больших Вязёмах'),
array('name' => 'Борки',	'secondName' => 'Борках'),
array('name' => 'Брёхово',	'secondName' => 'Брёхово'),
array('name' => 'Бужарово',	'secondName' => 'Бужарово'),
array('name' => 'Булатниково',	'secondName' => 'Булатниково'),
array('name' => 'Бурцево',	'secondName' => 'Бурцево'),
array('name' => 'Бутово',	'secondName' => 'Бутово'),
array('name' => 'Быково',	'secondName' => 'Быково'),
array('name' => 'Валищево',	'secondName' => 'Валищево'),
array('name' => 'Валуево',	'secondName' => 'Валуево'),
array('name' => 'Васькино',	'secondName' => 'Васькино'),
array('name' => 'Ватутинки',	'secondName' => 'Ватутинках'),
array('name' => 'Ваулово',	'secondName' => 'Ваулово'),
array('name' => 'Вельяминово',	'secondName' => 'Вельяминово'),
array('name' => 'Венюково',	'secondName' => 'Венюково'),
array('name' => 'Верея',	'secondName' => 'Верее'),
array('name' => 'Верхнее Мячково',	'secondName' => 'Верхнем Мячково'),
array('name' => 'Вёшки',	'secondName' => 'Вёшках'),
array('name' => 'Владимировка',	'secondName' => 'Владимировке'),
array('name' => 'Власиха',	'secondName' => 'Власихе'),
array('name' => 'Власово',	'secondName' => 'Власово'),
array('name' => 'Внуково',	'secondName' => 'Внуково'),
array('name' => 'Волокамск',	'secondName' => 'Волокамске'),
array('name' => 'Вороново',	'secondName' => 'Вороново'),
array('name' => 'Воскресенское',	'secondName' => 'Воскресенском'),
array('name' => 'Востряково',	'secondName' => 'Востряково'),
array('name' => 'Гаврилково',	'secondName' => 'Гаврилково'),
array('name' => 'Ганусово',	'secondName' => 'Ганусово'),
array('name' => 'Гжель',	'secondName' => 'Гжели'),
array('name' => 'Глаголево',	'secondName' => 'Глаголево'),
array('name' => 'Говорово',	'secondName' => 'Говорово'),
array('name' => 'Горки Ленинские',	'secondName' => 'Горках Ленинских'),
array('name' => 'Грибки',	'secondName' => 'Грибках'),
array('name' => 'Гривно',	'secondName' => 'Гривно'),
array('name' => 'Гришенки',	'secondName' => 'Гришенках'),
array('name' => 'Гряды',	'secondName' => 'Грядах'),
array('name' => 'Дарьино',	'secondName' => 'Дарьино'),
array('name' => 'Деденево',	'secondName' => 'Деденево'),
array('name' => 'Десна',	'secondName' => 'Десне'),
array('name' => 'Долматово',	'secondName' => 'Долматово'),
array('name' => 'Дрожжино',	'secondName' => 'Дрожжино'),
array('name' => 'Дудкино',	'secondName' => 'Дудкино'),
array('name' => 'Дурыкино',	'secondName' => 'Дурыкино'),
array('name' => 'Дылдино',	'secondName' => 'Дылдино'),
array('name' => 'Ермолино',	'secondName' => 'Ермолино'),
array('name' => 'Ершово',	'secondName' => 'Ершово'),
array('name' => 'Есино',	'secondName' => 'Есино'),
array('name' => 'Жабкино',	'secondName' => 'Жабкино'),
array('name' => 'Жаворонки',	'secondName' => 'Жаворонках'),
array('name' => 'Жилино',	'secondName' => 'Жилино'),
array('name' => 'Жостово',	'secondName' => 'Жостово'),
array('name' => 'Жуковка',	'secondName' => 'Жуковке'),
array('name' => 'Жулебино',	'secondName' => 'Жулебино'),
array('name' => 'Загорянский',	'secondName' => 'Загорянском'),
array('name' => 'Заречье',	'secondName' => 'Заречье'),
array('name' => 'Зеленоград',	'secondName' => 'Зеленограде'),
array('name' => 'Ивантеевка',	'secondName' => 'Ивантеевке'),
array('name' => 'Икша',	'secondName' => 'Икше'),
array('name' => 'Ильинское',	'secondName' => 'Ильинском'),
array('name' => 'Калининец',	'secondName' => 'Калининце'),
array('name' => 'Калиновка',	'secondName' => 'Калиновке'),
array('name' => 'Калчуга',	'secondName' => 'Калчуге'),
array('name' => 'Картино',	'secondName' => 'Картино'),
array('name' => 'Картмазово',	'secondName' => 'Картмазово'),
array('name' => 'Киевское',	'secondName' => 'Киевском'),
array('name' => 'Клязьма',	'secondName' => 'Клязьме'),
array('name' => 'Козенки',	'secondName' => 'Козенках'),
array('name' => 'Колонтаево',	'secondName' => 'Колонтаево'),
array('name' => 'Коммунарка',	'secondName' => 'Коммунарке'),
array('name' => 'Константиново',	'secondName' => 'Константиново'),
array('name' => 'Коренёво',	'secondName' => 'Коренёво'),
array('name' => 'Коробово',	'secondName' => 'Коробово'),
array('name' => 'Коростово',	'secondName' => 'Коростово'),
array('name' => 'Косино',	'secondName' => 'Косино'),
array('name' => 'Красково',	'secondName' => 'Красково'),
array('name' => 'Красная Пахра',	'secondName' => 'Красной Пахре'),
array('name' => 'Красный Поселок',	'secondName' => 'Красном Поселке'),
array('name' => 'Красный Путь',	'secondName' => 'Красный Путь'),
array('name' => 'Кратово',	'secondName' => 'Кратово'),
array('name' => 'Крёкшино',	'secondName' => 'Крёкшино'),
array('name' => 'Крюково',	'secondName' => 'Крюково'),
array('name' => 'Кудиново',	'secondName' => 'Кудиново'),
array('name' => 'Кунцево',	'secondName' => 'Кунцево'),
array('name' => 'Купавна',	'secondName' => 'Купавне'),
array('name' => 'Куркино',	'secondName' => 'Куркино'),
array('name' => 'Кутузово',	'secondName' => 'Кутузово'),
array('name' => 'Лайково',	'secondName' => 'Лайково'),
array('name' => 'Лапшинка',	'secondName' => 'Лапшинке'),
array('name' => 'Лесной Городок',	'secondName' => 'Лесном Городке'),
array('name' => 'Лианозово',	'secondName' => 'Лианозово'),
array('name' => 'Лопатино',	'secondName' => 'Лопатино'),
array('name' => 'Лунёво',	'secondName' => 'Лунёво'),
array('name' => 'Львовский',	'secondName' => 'Львовском'),
array('name' => 'Любучаны',	'secondName' => 'Любучанах'),
array('name' => 'Малаховка',	'secondName' => 'Малаховке'),
array('name' => 'Малые Вязёмы',	'secondName' => 'Малых Вязёмах'),
array('name' => 'Мальцы',	'secondName' => 'Мальцах'),
array('name' => 'Мамоново',	'secondName' => 'Мамоново'),
array('name' => 'Мамонтовка',	'secondName' => 'Мамонтовке'),
array('name' => 'Манушкино',	'secondName' => 'Манушкино'),
array('name' => 'Мартемьяново',	'secondName' => 'Мартемьяново'),
array('name' => 'Марусино',	'secondName' => 'Марусино'),
array('name' => 'Марушкино',	'secondName' => 'Марушкино'),
array('name' => 'Марфино',	'secondName' => 'Марфино'),
array('name' => 'Марьино',	'secondName' => 'Марьино'),
array('name' => 'Медвежьи Озёра',	'secondName' => 'Медвежьих Озёрах'),
array('name' => 'Мелихово',	'secondName' => 'Мелихово'),
array('name' => 'Мильково',	'secondName' => 'Мильково'),
array('name' => 'Мисайлово',	'secondName' => 'Мисайлово'),
array('name' => 'Михнево',	'secondName' => 'Михнево'),
array('name' => 'Мозжинка',	'secondName' => 'Мозжинке'),
array('name' => 'Молоденово',	'secondName' => 'Молоденово'),
array('name' => 'Молоди',	'secondName' => 'Молодях'),
array('name' => 'Молоково',	'secondName' => 'Молоково'),
array('name' => 'Монино',	'secondName' => 'Монино'),
array('name' => 'Мякинино',	'secondName' => 'Мякинино'),
array('name' => 'Нагорное',	'secondName' => 'Нагорном'),
array('name' => 'Назарьево',	'secondName' => 'Назарьево'),
array('name' => 'Нахабино',	'secondName' => 'Нахабино'),
array('name' => 'Некрасовка',	'secondName' => 'Некрасовке'),
array('name' => 'Некрасовский',	'secondName' => 'Некрасовском'),
array('name' => 'Немчиновка',	'secondName' => 'Немчиновком'),
array('name' => 'Нижнее Мячково',	'secondName' => 'Нижнем Мячково'),
array('name' => 'Николо-Урюпино',	'secondName' => 'Николо-Урюпино'),
array('name' => 'Новая Купавна',	'secondName' => 'Новой Купавне'),
array('name' => 'Новоивановское',	'secondName' => 'Новоивановском'),
array('name' => 'Новокосино',	'secondName' => 'Новокосино'),
array('name' => 'Новоподрезково',	'secondName' => 'Новоподрезково'),
array('name' => 'Новоселки',	'secondName' => 'Новоселках'),
array('name' => 'Новый Быт',	'secondName' => 'Новом Быту'),
array('name' => 'Обухово',	'secondName' => 'Обухово'),
array('name' => 'Обушково',	'secondName' => 'Обушково'),
array('name' => 'Озерецкое',	'secondName' => 'Озерецком'),
array('name' => 'Оксино',	'secondName' => 'Оксино'),
array('name' => 'Октябрьское',	'secondName' => 'Октябрьском'),
array('name' => 'Опалиха',	'secondName' => 'Опалихе'),
array('name' => 'Ордынцы',	'secondName' => 'Ордынцах'),
array('name' => 'Останкино',	'secondName' => 'Останкино'),
array('name' => 'Остафьево',	'secondName' => 'Остафьево'),
array('name' => 'Островцы',	'secondName' => 'Островцах'),
array('name' => 'Очаково',	'secondName' => 'Очаково'),
array('name' => 'п. Володарского',	'secondName' => 'п. Володарского'),
array('name' => 'Павловская Слобода',	'secondName' => 'Павловской Слободе'),
array('name' => 'Павшино',	'secondName' => 'Павшино'),
array('name' => 'Падиково',	'secondName' => 'Падиково'),
array('name' => 'Пахра',	'secondName' => 'Пахре'),
array('name' => 'Первомайское',	'secondName' => 'Первомайском'),
array('name' => 'Переделкино',	'secondName' => 'Переделкино'),
array('name' => 'Перхурово',	'secondName' => 'Перхурово'),
array('name' => 'Пестово',	'secondName' => 'Пестово'),
array('name' => 'Петрово-Дальнее',	'secondName' => 'Петрово-Дальнее'),
array('name' => 'Пирогово',	'secondName' => 'Пирогово'),
array('name' => 'Поварово',	'secondName' => 'Поварово'),
array('name' => 'Подлипки',	'secondName' => 'Подлипках'),
array('name' => 'Подрезково',	'secondName' => 'Подрезково'),
array('name' => 'Подушкино',	'secondName' => 'Подушкино'),
array('name' => 'Покров',	'secondName' => 'Покрове'),
array('name' => 'Покровское',	'secondName' => 'Покровском'),
array('name' => 'пос. им. Воровского',	'secondName' => 'пос. им. Воровского'),
array('name' => 'Починки',	'secondName' => 'Починках'),
array('name' => 'Поярково',	'secondName' => 'Поярково'),
array('name' => 'Пролетарский',	'secondName' => 'Пролетарском'),
array('name' => 'Птичное',	'secondName' => 'Птичное'),
array('name' => 'Пуршево',	'secondName' => 'Пуршево'),
array('name' => 'Путилково',	'secondName' => 'Путилково'),
array('name' => 'Развилка',	'secondName' => 'Развилке'),
array('name' => 'Раздоры',	'secondName' => 'Раздорах'),
array('name' => 'Раменки',	'secondName' => 'Раменках'),
array('name' => 'Рассказовка',	'secondName' => 'Рассказовках'),
array('name' => 'Рассудово',	'secondName' => 'Рассудово'),
array('name' => 'Расторгуево',	'secondName' => 'Расторгуево'),
array('name' => 'Растуново',	'secondName' => 'Растуново'),
array('name' => 'Репниково',	'secondName' => 'Репниково'),
array('name' => 'Речник',	'secondName' => 'Речнике'),
array('name' => 'Ржавки',	'secondName' => 'Ржавках'),
array('name' => 'Родники',	'secondName' => 'Родниках'),
array('name' => 'Рождественно',	'secondName' => 'Рождественно'),
array('name' => 'Рублёво',	'secondName' => 'Рублёво'),
array('name' => 'Румянцево',	'secondName' => 'Румянцево'),
array('name' => 'Рыболово',	'secondName' => 'Рыболово'),
array('name' => 'Рылеево',	'secondName' => 'Рылеево'),
array('name' => 'Сабурово',	'secondName' => 'Сабурово'),
array('name' => 'Саврасово',	'secondName' => 'Саврасово'),
array('name' => 'Саларьево',	'secondName' => 'Саларьево'),
array('name' => 'Салтыковка',	'secondName' => 'Салтыковке'),
array('name' => 'Сареево',	'secondName' => 'Сареево'),
array('name' => 'Северный',	'secondName' => 'Северном'),
array('name' => 'Селятино',	'secondName' => 'Селятино'),
array('name' => 'Серебряный бор',	'secondName' => 'Серебряном бору'),
array('name' => 'Сетунь Малая',	'secondName' => 'Сетуни Малой'),
array('name' => 'Синьково',	'secondName' => 'Синьково'),
array('name' => 'Сколково',	'secondName' => 'Сколково'),
array('name' => 'Снегири',	'secondName' => 'Снегирях'),
array('name' => 'Солнышково',	'secondName' => 'Солнышково'),
array('name' => 'Софрино',	'secondName' => 'Софрино'),
array('name' => 'Софьино',	'secondName' => 'Софьино'),
array('name' => 'Столбовая',	'secondName' => 'Столбовой'),
array('name' => 'Стремилово',	'secondName' => 'Стремилово'),
array('name' => 'Строгино',	'secondName' => 'Строгино'),
array('name' => 'Сумино',	'secondName' => 'Сумино'),
array('name' => 'Суханово',	'secondName' => 'Суханово'),
array('name' => 'Сходня',	'secondName' => 'Сходне'),
array('name' => 'Сынково',	'secondName' => 'Сынково'),
array('name' => 'Сычево',	'secondName' => 'Сычево'),
array('name' => 'Талеж',	'secondName' => 'Талеже'),
array('name' => 'Талицы',	'secondName' => 'Талицах'),
array('name' => 'Тарасовка',	'secondName' => 'Тарасовке'),
array('name' => 'Тарычёво',	'secondName' => 'Тарычёво'),
array('name' => 'Таширово',	'secondName' => 'Таширово'),
array('name' => 'Терехово',	'secondName' => 'Терехово'),
array('name' => 'Тимонино',	'secondName' => 'Тимонино'),
array('name' => 'Толстопальцево',	'secondName' => 'Толстопальцево'),
array('name' => 'Томилино',	'secondName' => 'Томилино'),
array('name' => 'Трёхгорки',	'secondName' => 'Трёхгорках'),
array('name' => 'Троицк',	'secondName' => 'Троицке'),
array('name' => 'Тушино',	'secondName' => 'Тушино'),
array('name' => 'Усово',	'secondName' => 'Усово'),
array('name' => 'Успенское',	'secondName' => 'Успенском'),
array('name' => 'Ухтомская',	'secondName' => 'Ухтомской'),
array('name' => 'Федоскино',	'secondName' => 'Федоскино'),
array('name' => 'Федюково',	'secondName' => 'Федюково'),
array('name' => 'Филипповское',	'secondName' => 'Филипповской'),
array('name' => 'Фирсановка',	'secondName' => 'Фирсановке'),
array('name' => 'Ховрино',	'secondName' => 'Ховрино'),
array('name' => 'Часцы',	'secondName' => 'Часцах'),
array('name' => 'Чашниково',	'secondName' => 'Чашниково'),
array('name' => 'Челобитьево',	'secondName' => 'Челобитьево'),
array('name' => 'Чепелёво',	'secondName' => 'Чепелёво'),
array('name' => 'Шарапова Охота',	'secondName' => 'Шараповой Охоте'),
array('name' => 'Шарапово',	'secondName' => 'Шарапово'),
array('name' => 'Щапово',	'secondName' => 'Щапово'),
array('name' => 'Щербинка',	'secondName' => 'Щербинке'),
array('name' => 'Юдино',	'secondName' => 'Юдино'),
array('name' => 'Юрлово',	'secondName' => 'Юрлово'),
array('name' => 'Язово',	'secondName' => 'Язово'),
array('name' => 'Ям',	'secondName' => 'Яме ')
);

?>